#------------------------------------------------------------------------------
# Конфиг для Flowcharting в Grafana с переносом текста
cellIdPreamble: "cell-"
cells:
  tonometr_block:
    dataRef: "tonometr_value"
    label:
      text: "Тонометр:\n${tonometr_value}"
      decimalPoints: 0
      units: "none"
      labelColor:
        color: "white"
      style: |
        white-space: pre;
        text-align: center;
        font-size: 14px;
        line-height: 1.3;

  termometr_block:
    dataRef: "termometr_value"
    label:
      text: "Термометр:\n${termometr_value}"
      decimalPoints: 0
      units: "none"
      labelColor:
        color: "white"
      style: |
        white-space: pre;
        text-align: center;
        font-size: 14px;
        line-height: 1.3;

  internet_block:
    dataRef: "internet_value"
    label:
      text: "Интернет:\n${internet_value}"
      decimalPoints: 0
      units: "none"
      labelColor:
        color: "white"
      style: |
        white-space: pre;
        text-align: center;
        font-size: 14px;
        line-height: 1.3;

  printer_block:
    dataRef: "printer_value"
    label:
      text: "Принтер:\n${printer_value}"
      decimalPoints: 0
      units: "none"
      labelColor:
        color: "white"
      style: |
        white-space: pre;
        text-align: center;
        font-size: 14px;
        line-height: 1.3;

  internal_requests_block:
    dataRef: "internal_value"
    label:
      text: "Внутренние\nзаявки:\n${internal_value}"
      decimalPoints: 0
      units: "none"
      labelColor:
        color: "white"
      style: |
        white-space: pre;
        text-align: center;
        font-size: 12px;
        line-height: 1.3;

  planned_preventive_maintenance_block:
    dataRef: "preventive_value"
    label:
      text: "Планово-\nпрофилактические\nработы:\n${preventive_value}"
      decimalPoints: 0
      units: "none"
      labelColor:
        color: "white"
      style: |
        white-space: pre;
        text-align: center;
        font-size: 12px;
        line-height: 1.3;

  other_block:
    dataRef: "other_value"
    label:
      text: "Другое:\n${other_value}"
      decimalPoints: 0
      units: "none"
      labelColor:
        color: "white"
      style: |
        white-space: pre;
        text-align: center;
        font-size: 14px;
        line-height: 1.3;

  malfunction_block:
    dataRef: "malfunction_value"
    label:
      text: "Нарушение в\nработе комплекса:\n${malfunction_value}"
      decimalPoints: 0
      units: "none"
      labelColor:
        color: "white"
      style: |
        white-space: pre;
        text-align: center;
        font-size: 12px;
        line-height: 1.3;

  replacement_block:
    dataRef: "replacement_value"
    label:
      text: "Замена\nкомплектующих:\n${replacement_value}"
      decimalPoints: 0
      units: "none"
      labelColor:
        color: "white"
      style: |
        white-space: pre;
        text-align: center;
        font-size: 12px;
        line-height: 1.3;

  delivery_block:
    dataRef: "delivery_value"
    label:
      text: "Доставка\nматериалов:\n${delivery_value}"
      decimalPoints: 0
      units: "none"
      labelColor:
        color: "white"
      style: |
        white-space: pre;
        text-align: center;
        font-size: 12px;
        line-height: 1.3;

  transfer_block:
    dataRef: "transfer_value"
    label:
      text: "Перенос\nкомплекса:\n${transfer_value}"
      decimalPoints: 0
      units: "none"
      labelColor:
        color: "white"
      style: |
        white-space: pre;
        text-align: center;
        font-size: 12px;
        line-height: 1.3;
