#------------------------------------------------------------------------------
# Конфиг для Flowcharting в Grafana
# Связывает элемент draw.io (tonometr_blok) с SQL-запросом
cellIdPreamble: "cell-"
cells:
  tonometr_block:  # Блок тонометра
    dataRef: "tonometr_value"  # Метрика из SQL-запроса
    label:
      separator: "space"
      decimalPoints: 0
      units: "none"
      labelColor:
        color: "white"
      style: "white-space: pre-wrap; word-wrap: break-word;"
  termometr_block:  # Блок термометра
    dataRef: "termometr_value"  # Метрика из SQL-запроса
    label:
     separator: "space"
     decimalPoints: 0
     units: "none"
     labelColor:
       color: "white"
     style: "white-space: pre-wrap; word-wrap: break-word;"
  internet_block:  # Блок интернета
    dataRef: "internet_value"  # Метрика из SQL-запроса
    label:
     separator: "space"
     decimalPoints: 0
     units: "none"
     labelColor:
       color: "white"
     style: "white-space: pre-wrap; word-wrap: break-word;"
  printer_block:  # Блок принтера
    dataRef: "printer_value"  # Метрика из SQL-запроса
    label:
     separator: "space"
     decimalPoints: 0
     units: "none"
     labelColor:
       color: "white"
     style: "white-space: pre-wrap; word-wrap: break-word;"
  internal_requests_block:  # Блок внутренние заявки
    dataRef: "internal_value"  # Метрика из SQL-запроса
    label:
     separator: "space"
     decimalPoints: 0
     nits: "none"
     labelColor:
       color: "white"
     style: "white-space: pre-wrap; word-wrap: break-word;"
  planned_preventive_maintenance_block: # Блок планово профилактические работы ППР
    dataRef: "preventive_value"  # Метрика из SQL-запроса
    label:
     separator: "space"
     decimalPoints: 0
     nits: "none"
     labelColor:
       color: "white"
     style: "white-space: pre-wrap; word-wrap: break-word;"
  other_block: # Блок Другое
    dataRef: "other_value"  # Метрика из SQL-запроса
    label:
     separator: "space"
     decimalPoints: 0
     nits: "none"
     labelColor:
       color: "white"
     style: "white-space: pre-wrap; word-wrap: break-word;"
  malfunction_block: # Блок нарушение в работе комплекса
    dataRef: "malfunction_value"  # Метрика из SQL-запроса
    label:
      separator: "space"
      decimalPoints: 0
      nits: "none"
      labelColor:
        color: "white"
      style: "white-space: pre-wrap; word-wrap: break-word;"
  replacement_block: # Замена одного или нескольких комплектующих в комплексе
    dataRef: "replacement_value"  # Метрика из SQL-запроса
    label:
      separator: "space"
      decimalPoints: 0
      nits: "none"
      labelColor:
        color: "white"
      style: "white-space: pre-wrap; word-wrap: break-word;"
  delivery_block: # Доставка расходных материалов
    dataRef: "delivery_value"  # Метрика из SQL-запроса
    label:
      separator: "space"
      decimalPoints: 0
      nits: "none"
      labelColor:
        color: "white"
      style: "white-space: pre-wrap; word-wrap: break-word;"
  transfer_block: # Блок Перенос комплекса
    dataRef: "transfer_value"  # Метрика из SQL-запроса
    label:
      separator: "space"
      decimalPoints: 0
      nits: "none"
      labelColor:
        color: "white"
      style: "white-space: pre-wrap; word-wrap: break-word;"
